# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{sloono}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Peter Suschlik"]
  s.date = %q{2011-03-03}
  s.email = %q{peter-sloono@suschlik.de}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     ".rvmrc",
     ".watchr",
     "README.rdoc",
     "Rakefile",
     "lib/sloono.rb",
     "lib/sloono/extensions.rb",
     "lib/sloono/request.rb",
     "lib/sloono/response.rb",
     "lib/sloono/sms.rb",
     "test/helper.rb",
     "test/notify_report.rb",
     "test/test_sloono.rb",
     "test/test_sloono_extensions.rb",
     "test/test_sloono_request.rb",
     "test/test_sloono_response.rb",
     "test/test_sloono_sms.rb"
  ]
  s.homepage = %q{http://github.com/splattael/sloono}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{SMS API for sloono.de}
  s.test_files = [
    "test/test_sloono.rb",
     "test/test_sloono_request.rb",
     "test/test_sloono_response.rb",
     "test/test_sloono_extensions.rb",
     "test/test_sloono_sms.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<typhoeus>, [">= 0.1.10"])
      s.add_development_dependency(%q<riot>, ["= 0.10.9"])
      s.add_development_dependency(%q<riot_notifier>, ["= 0.0.7"])
    else
      s.add_dependency(%q<typhoeus>, [">= 0.1.10"])
      s.add_dependency(%q<riot>, ["= 0.10.9"])
      s.add_dependency(%q<riot_notifier>, ["= 0.0.7"])
    end
  else
    s.add_dependency(%q<typhoeus>, [">= 0.1.10"])
    s.add_dependency(%q<riot>, ["= 0.10.9"])
    s.add_dependency(%q<riot_notifier>, ["= 0.0.7"])
  end
end

